In [2]:
import numpy as np
print(np.__version__)	# 1.16.3

1.19.5


In [9]:
my_arr = np.array([[10, 20, 30], [40, 50, 60]])
print(my_arr)
# [[10 20 30]
#  [40 50 60]]

[[10 20 30]
 [40 50 60]]


In [11]:
type(my_arr)
#numpy.ndarray

numpy.ndarray

In [12]:
my_arr[0][2]	# 30

30

In [13]:
np.sum(my_arr)	# 210

210